# Generated by Django 6.0.3 on 2026-03-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ojtprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
