# Generated by Django 6.0.3 on 2026-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='intern_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='program',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ojtprofile',
            name='trainee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
