# Generated by Django 6.0.3 on 2026-03-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ojtprofile_department_ojtprofile_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtprofile',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('supervisor', 'Supervisor'), ('hr', 'HR'), ('guard', 'Guard')], default='intern', max_length=20),
        ),
    ]
